/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package butchershop;

import java.awt.Color;
import java.awt.Container;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.EtchedBorder;
import javax.swing.border.LineBorder;

/**
 *
 * @author Angel
 */
public class CierreCaja extends javax.swing.JFrame{

    
    /**
     Variables
     */
    IniciarDia atras;
    String fechaHoy;
    public CierreCaja(IniciarDia atras, String ventas, String gastos, String caja, String fechaHoy) {
        initComponents();
        this.atras = atras;
        this.fechaHoy = fechaHoy;
        labelVentas.setText(ventas);
        labelGastos.setText(gastos);
        labelCaja.setText(caja);
        totalSupuesto.setText(String.valueOf(Integer.parseInt(ventas)-Integer.parseInt(gastos)));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelVentas = new javax.swing.JLabel();
        labelGastos = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalSupuesto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputBilletes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputMonedas = new javax.swing.JTextField();
        labelCaja = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(120, 0), new java.awt.Dimension(120, 0), new java.awt.Dimension(120, 32767));
        jLabel7 = new javax.swing.JLabel();
        totalRealizado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        labelDiferencia = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelEfectivo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelTotalDeposito = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        inputTarjeta = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        Fondo1 = new javax.swing.JLabel();

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/foto toro.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(950, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Total Ventas:");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, 26));

        labelVentas.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVentas.setText("0");
        labelVentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        labelVentas.setOpaque(true);
        getContentPane().add(labelVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 160, 40));

        labelGastos.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelGastos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGastos.setText("0");
        labelGastos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        labelGastos.setOpaque(true);
        getContentPane().add(labelGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 156, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("Total Gastos:");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 150, 26));

        totalSupuesto.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        totalSupuesto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalSupuesto.setText("0");
        totalSupuesto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        totalSupuesto.setOpaque(true);
        getContentPane().add(totalSupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 156, 40));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setText("Total:");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, 26));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Billetes +");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 100, -1));

        inputBilletes.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        inputBilletes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputBilletes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBilletesActionPerformed(evt);
            }
        });
        inputBilletes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputBilletesKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputBilletesKeyTyped(evt);
            }
        });
        getContentPane().add(inputBilletes, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 153, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("Monedas +");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 120, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setText("Caja   -");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 80, -1));

        inputMonedas.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        inputMonedas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputMonedas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputMonedasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputMonedasKeyTyped(evt);
            }
        });
        getContentPane().add(inputMonedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 153, -1));

        labelCaja.setEditable(false);
        labelCaja.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelCaja.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        labelCaja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        labelCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelCajaActionPerformed(evt);
            }
        });
        getContentPane().add(labelCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 252, 153, 40));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 178, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setText("Total:");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 61, -1));

        totalRealizado.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        totalRealizado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalRealizado.setText("0");
        totalRealizado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        totalRealizado.setOpaque(true);
        getContentPane().add(totalRealizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 302, 160, 40));

        jButton1.setBackground(new java.awt.Color(0, 51, 255));
        jButton1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Guardar Cambios>>>");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 570, 386, 113));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel9.setText("Diferencia: ");
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, 32));

        labelDiferencia.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelDiferencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDiferencia.setText("0");
        labelDiferencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        labelDiferencia.setOpaque(true);
        getContentPane().add(labelDiferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 153, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel11.setText("Cierre");
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 126, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel12.setText("Saldo Supuesto");
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, 51));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel13.setText("Saldo Realizado");
        jLabel13.setOpaque(true);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 304, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel14.setText("Deposito Efectivo +");
        jLabel14.setOpaque(true);
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, 30));

        labelEfectivo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelEfectivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEfectivo.setText("0");
        labelEfectivo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        labelEfectivo.setOpaque(true);
        getContentPane().add(labelEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 160, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setText("Deposito Tarjeta +");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, -1, -1));

        labelTotalDeposito.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelTotalDeposito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTotalDeposito.setText("0");
        labelTotalDeposito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        labelTotalDeposito.setOpaque(true);
        getContentPane().add(labelTotalDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 630, 160, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setText("Total a depositar:");
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, -1, -1));

        inputTarjeta.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        inputTarjeta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputTarjetaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTarjetaKeyTyped(evt);
            }
        });
        getContentPane().add(inputTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, 155, -1));

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("<<<Atras");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 70));

        Fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/foto toro.jpg"))); // NOI18N
        getContentPane().add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 0, 1100, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputBilletesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBilletesActionPerformed
        // 
        System.out.println(inputBilletes);
        System.out.println(inputMonedas);
        System.out.println(labelCaja);
    }//GEN-LAST:event_inputBilletesActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Guarda todos los cambios dados.
        if(inputMonedas.getText().isEmpty() || inputBilletes.getText().isEmpty() || inputTarjeta.getText().isEmpty() ){
            Border borderError = new LineBorder(Color.red,2);
            if(inputMonedas.getText().isEmpty())inputMonedas.setBorder(borderError);
            else inputMonedas.setBorder(new EtchedBorder());
            if(inputBilletes.getText().isEmpty())inputBilletes.setBorder(borderError);
            else inputBilletes.setBorder(new EtchedBorder());
            if(inputTarjeta.getText().isEmpty())inputTarjeta.setBorder(borderError);
            else inputTarjeta.setBorder(new EtchedBorder());
            JOptionPane.showMessageDialog(this, "Error: No puede haber espacios vacios.");
        }else{
            atras.documento.setCaja(atras.atras, Integer.parseInt(inputMonedas.getText()));
            atras.documento.setData("Billetes", Integer.parseInt(inputBilletes.getText()));
            atras.documento.setData("Monedas", Integer.parseInt(inputMonedas.getText()));
            atras.documento.setData("TotalTarjeta", Integer.parseInt(inputTarjeta.getText()));
            atras.documento.updateFormulas();
            atras.documento.saveWordBook();
            atras.documento = atras.atras.newDocument(fechaHoy);

            //cierra todo hasta regresar al menu principal
            atras.atras.setVisible(true);
            atras.dispose();
            
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void inputBilletesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputBilletesKeyTyped
        // TODO add your handling code here:
        char tecla =  evt.getKeyChar();
        if(Character.isLetter(tecla)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingresar solo Numeros.");
        }
    }//GEN-LAST:event_inputBilletesKeyTyped

    private void inputMonedasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputMonedasKeyTyped
        // TODO add your handling code here:
        char tecla =  evt.getKeyChar();
        if(Character.isLetter(tecla)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingresar solo Numeros.");
        }
    }//GEN-LAST:event_inputMonedasKeyTyped

    private void inputTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTarjetaKeyTyped
        // TODO add your handling code here:
        char tecla =  evt.getKeyChar();
        if(Character.isLetter(tecla)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingresar solo Numeros.");
        }
    }//GEN-LAST:event_inputTarjetaKeyTyped

    private void inputBilletesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputBilletesKeyReleased
        // TODO add your handling code here:
        inputBilletes.setText(inputBilletes.getText().trim());
        this.updateView();

    }//GEN-LAST:event_inputBilletesKeyReleased

    private void inputMonedasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputMonedasKeyReleased
        // TODO add your handling code here:
        inputMonedas.setText(inputMonedas.getText().trim());
        this.updateView();
    }//GEN-LAST:event_inputMonedasKeyReleased

    private void inputTarjetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTarjetaKeyReleased
        // TODO add your handling code here:
        inputTarjeta.setText(inputTarjeta.getText().trim());
        this.updateView();
    }//GEN-LAST:event_inputTarjetaKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Boton atras para regresar a IniciarDia()
        atras.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void labelCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelCajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelCajaActionPerformed

    //Funciones usadas en el cierre de caja
    public void updateView(){
        String billetes = this.inputBilletes.getText();
        String monedas = this.inputMonedas.getText();
        String tarjeta = this.inputTarjeta.getText();
        int caja = Integer.parseInt(this.labelCaja.getText());
        int b = 0;
        int m = 0;
        int t = 0;
        if(!billetes.isEmpty()){
            b = Integer.parseInt(billetes);
            if(!monedas.isEmpty()){
                m = Integer.parseInt(monedas);
                if(!tarjeta.isEmpty()){
                    t = Integer.parseInt(tarjeta);
                }
            }
        }
        this.labelEfectivo.setText(String.valueOf(b));
        this.totalRealizado.setText(String.valueOf((b+m)-caja));
        this.labelDiferencia.setText(String.valueOf(Integer.parseInt(this.totalRealizado.getText())-Integer.parseInt(this.totalSupuesto.getText())));
        this.labelTotalDeposito.setText(String.valueOf(b+t));
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Fondo1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JTextField inputBilletes;
    private javax.swing.JTextField inputMonedas;
    private javax.swing.JTextField inputTarjeta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField labelCaja;
    private javax.swing.JLabel labelDiferencia;
    private javax.swing.JLabel labelEfectivo;
    private javax.swing.JLabel labelGastos;
    private javax.swing.JLabel labelTotalDeposito;
    private javax.swing.JLabel labelVentas;
    private javax.swing.JLabel totalRealizado;
    private javax.swing.JLabel totalSupuesto;
    // End of variables declaration//GEN-END:variables

   
}
