/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package butchershop;
import java.awt.ComponentOrientation;
import java.awt.JobAttributes;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
/**
 *
 * @author Angel
 */
public class IniciarDia extends javax.swing.JFrame {

    /**
     * Creates new form IniciarDia
     */
    //Variables globales
    DefaultListModel modelVenta = new DefaultListModel();
    DefaultListModel modelGasto = new DefaultListModel();
    List ventas;
    List gastos;
    Excel documento;
    MenuInicio atras;
    Fiados fiados;
    public IniciarDia(MenuInicio atras, Excel documento) {
        initComponents();
        //asigna variables globales
        this.atras = atras;
        this.documento = documento;
        ventas = documento.getPrecios(true);
        gastos = documento.getPrecios(false);
        //centra los jlist
        DefaultListCellRenderer cellRenderer = (DefaultListCellRenderer)jList1.getCellRenderer();
        cellRenderer.setHorizontalAlignment(SwingConstants .CENTER);
        DefaultListCellRenderer cellRenderer2 = (DefaultListCellRenderer)jList2.getCellRenderer();
        cellRenderer2.setHorizontalAlignment(SwingConstants .CENTER);
   
        LabelFecha.setText(this.documento.todayDate());//Dar la fecha de hoy en la vista
        LabelCaja.setText(String.valueOf(this.documento.getData("Caja")));
        //Verifica si necesita agregar la lista al model
        
        
        if(!ventas.isEmpty()){
            modelVenta.addAll(ventas);
            labelTotalVentas.setText(getSumaModel(modelVenta));
        }
        if(!gastos.isEmpty()){
            modelGasto.addAll(gastos);
            labelTotalGastos.setText(getSumaModel(modelGasto));
        }
        jList1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jList1.setModel(modelVenta);
        jList2.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jList2.setModel(modelGasto);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        labelTotalVentas = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        LabelFecha = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelTotalGastos = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        LabelCaja = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Venta", "Gasto" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 179, 50));

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Agregar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 243, 50));

        jTextField1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setToolTipText("");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 320, 50));

        jList1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 1, 2, new java.awt.Color(0, 0, 0)));
        jList1.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 180, 240));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setText("Total:");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 100, 50));

        labelTotalVentas.setBackground(new java.awt.Color(255, 255, 255));
        labelTotalVentas.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        labelTotalVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTotalVentas.setText("0");
        labelTotalVentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        labelTotalVentas.setOpaque(true);
        getContentPane().add(labelTotalVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 180, 50));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ventas");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 8, 2, new java.awt.Color(0, 0, 0)));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 180, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMaximumSize(new java.awt.Dimension(0, 0));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 130, 130));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gastos");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 8, 2, new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 180, -1));

        jList2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 1, 2, new java.awt.Color(0, 0, 0)));
        jList2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 180, 240));

        LabelFecha.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LabelFecha.setText("12/12/2020");
        LabelFecha.setOpaque(true);
        getContentPane().add(LabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, 130, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("Fecha:");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 80, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel5.setText("Total:");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, 100, 50));

        labelTotalGastos.setBackground(new java.awt.Color(255, 255, 255));
        labelTotalGastos.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        labelTotalGastos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTotalGastos.setText("0");
        labelTotalGastos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        labelTotalGastos.setOpaque(true);
        getContentPane().add(labelTotalGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 490, 180, 50));

        jButton4.setBackground(new java.awt.Color(0, 102, 255));
        jButton4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Cierre del Dia >>>");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 550, 460, 113));

        jButton5.setBackground(new java.awt.Color(0, 102, 255));
        jButton5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("<<<Atras");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 7, 180, 73));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setText("Caja:");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 60, -1));

        LabelCaja.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LabelCaja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCaja.setText("0");
        LabelCaja.setOpaque(true);
        getContentPane().add(LabelCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 130, -1));

        jButton3.setText("Fiados");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 330, 70));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/foto toro.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 0, 1100, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Boton para Agregar precio a VENTAS/GASTOS
        this.addPrecio();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // BOTON PARA ELIMINAR UNA VENTA
        try{
            if(jList1.getSelectedIndex()==-1 && jList2.getSelectedIndex()==-1){
                JOptionPane.showMessageDialog(this, "Error: Selecionar un valor de la lista.");
            }else{
                String[] botones = {"Si","No"};
                if(jList1.getSelectedIndex()!=-1){//seleciono ventas                   
                    int indexSelected = jList1.getSelectedIndex();
                    int valor = JOptionPane.showOptionDialog(this, "¿Esta seguro de eliminar "+ ventas.get(indexSelected) +" en Ventas?", 
                            "Advertencia", 0, 0, null, botones, this);
                    if(valor==JOptionPane.NO_OPTION) return; //Si da a NO se detiene todo y no elimina nada.
                    ventas.remove(indexSelected);
                    modelVenta.clear();
                    modelVenta.addAll(ventas);
                    String sumaVentas =  getSumaModel(modelVenta);
                    labelTotalVentas.setText(sumaVentas);
                    ArrayList<String> list = this.defaultListModelToArrayList(modelVenta);
                    this.documento.setPrecios(true, list);
                }else{//seleciono gastos.
                    int indexSelected = jList2.getSelectedIndex();
                    int valor = JOptionPane.showOptionDialog(this, "¿Esta seguro de eliminar "+ gastos.get(indexSelected) +" en Gastos?", 
                            "Advertencia", 0, 0, null, botones, this);
                    if(valor==JOptionPane.NO_OPTION) return; //Si da a NO, Se detiene todo y no elimina nada.
                    gastos.remove(indexSelected);
                    modelGasto.clear();
                    modelGasto.addAll(gastos);
                    String sumaVentas =  getSumaModel(modelGasto);
                    labelTotalGastos.setText(sumaVentas);
                    ArrayList<String> list = this.defaultListModelToArrayList(modelGasto);
                    this.documento.setPrecios(false, list);
                }
                this.documento.updateFormulas();
                this.documento.saveWordBook();
                this.documento = atras.newDocument(this.LabelFecha.getText());
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error: "+e.toString());
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Boton para hacer cierre del dia.
        try{
            this.documento.updateFormulas();
            this.documento.saveWordBook();
            this.documento = atras.newDocument(this.LabelFecha.getText());
            CierreCaja cierrecaja = new CierreCaja(this, labelTotalVentas.getText(), labelTotalGastos.getText(),LabelCaja.getText(), this.LabelFecha.getText());
            this.setVisible(false);
            cierrecaja.setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error: "+e.toString());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Boton Atras pararetroceder en la ventana
        this.atras.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        char tecla =  evt.getKeyChar();
        if(Character.isLetter(tecla)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingresar solo Numeros.");
        }
      
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // deja de presiona la tecla.
        jTextField1.setText(jTextField1.getText().trim());
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            this.addPrecio();
        }
       
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        if(jList2.getSelectedIndex()!=-1){
            jList2.clearSelection();
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        // TODO add your handling code here:
        if(jList1.getSelectedIndex()!=-1){
            jList1.clearSelection();
        }
    }//GEN-LAST:event_jList2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(this.fiados==null){
            this.fiados = new Fiados(LabelFecha.getText());
        }
        this.fiados.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    //Metodos utilizados en el JFRAME
 
    public void addPrecio(){
        try {
            String tipoPrecio = (String) jComboBox1.getSelectedItem();
            if(!jTextField1.getText().isEmpty()){
                int Precio = Integer.parseInt(jTextField1.getText());//precio digitado en el campo de text.
                if(tipoPrecio=="Venta"){
                    ventas.add(0,Precio);
                    modelVenta.clear();
                    modelVenta.addAll(ventas);
                    String sumaVentas =  getSumaModel(modelVenta);
                    labelTotalVentas.setText(sumaVentas);
                    ArrayList list = this.defaultListModelToArrayList(modelVenta);
                    this.documento.setPrecios(true, list);                
                }
                else if(tipoPrecio=="Gasto"){
                    gastos.add(0,Precio);
                    modelGasto.clear();
                    modelGasto.addAll(gastos);
                    String sumaGastos =  getSumaModel(modelGasto);
                    labelTotalGastos.setText(sumaGastos);
                    ArrayList list = this.defaultListModelToArrayList(modelGasto);
                    this.documento.setPrecios(false, list);
                }
                this.documento.updateFormulas();
                this.documento.saveWordBook();
                this.documento = atras.newDocument(this.LabelFecha.getText());
                jTextField1.setText("");//reinicia el campo de texto del precio
            }else{
                JOptionPane.showMessageDialog(this, "Error: Espacio vacio.");
            }
        } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: "+e.toString());
        }
            
    }
/*
    Suma todos los datos agregados al modelo y 
    retorna el string de la suma.
    */
    public String getSumaModel(DefaultListModel model){
        int sumaTotal = 0;
        for(int i=0; i < model.getSize(); i++){
            sumaTotal += Integer.parseInt(model.getElementAt(i).toString());
        }
        
        return String.valueOf(sumaTotal);
    }
    public ArrayList<String> defaultListModelToArrayList(DefaultListModel model){
        ArrayList<String> Lista = new ArrayList();
        for (int i = 0; i < model.getSize(); i++) {
            Lista.add(model.get(i).toString());
        }
        return Lista;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel LabelCaja;
    private javax.swing.JLabel LabelFecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelTotalGastos;
    private javax.swing.JLabel labelTotalVentas;
    // End of variables declaration//GEN-END:variables
}
